### ISSUE TITLE
Better use of for and for each statements with variables in command arguments

### ISSUE THREAD

**Issue by lightwriter94** [PandawanFr/mcs#2]
I think what you have so far for and for each statements is very useful for mapmakers since sometimes like for me I will have 100s of similiar commands but just have to change 1 or 2 things...   however, I noticed the current setup doesn't support the variable being used as an argument or as a relative coordinate...
Something like this:

> function testing {
> 	for (var $y = 0; $y < 256; $y = $y + 1){
>           scoreboard players set @e[x=,y=$y,z=,r=1] locY $y;
>   }
> }
would generate something like this:

> scoreboard players set @e[x=,y=0,z=,r=1] locY 0
>scoreboard players set @e[x=,y=1,z=,r=1] locY 1
>scoreboard players set @e[x=,y=2,z=,r=1] locY 2
>scoreboard players set @e[x=,y=3,z=,r=1] locY 3
>and so on...
>scoreboard players set @e[x=,y=256,z=,r=1] locY 256

Instead, in the current version, it generates...
>scoreboard players set @e[x=,y=$y,z=,r=1] locY 0
same should apply for relative coordinates, exact coordinates, and other kind of argument such as scoreboard scores...

**Comment by Pandawan** [comment]
Hi, I'll have to look into this issue, I thought this was working. 

Edit: While you wait for the update, you should be able to do this:
```
scoreboard players set "@e[x=1,y=`return $hey`,r=1] locY 0"
```
Since strings compile into normal text, you can use an eval block to add your variable data.

**Comment by lightwriter94** [comment]
Thanks!  As a reference for anyone else who wants to this, here is an example:
`function test{
for (var $y = 0; $y < 256; $y = $y + 1){
scoreboard players set "@e[x=,y=`return $y`,z=,r=1] locY `return $y`";
}
}`
generates:

> scoreboard players set @e[x=,y=0,z=,r=1] locY 0
> scoreboard players set @e[x=,y=0,z=,r=1] locY 1
>and so on... (until 255)
