### ISSUE TITLE
Bug with execute in for and for each commands 

### ISSUE THREAD

**Issue by lightwriter94** [PandawanFr/mcs#3]
Anytime, I use an execute command in a for loop, I'm getting an error for the command that's trying to execute something when compiling...
For Example:

> function testing {
> 	for (var $y = 0; $y < 257; $y = $y + 1){
>       execute @e[score_test_min=0] ~ ~ ~ /say $y;
>   }
> }
gives me an error saying:

> Error:Unexpected token: {"type":"reg","value":"ay"}

if I don't include the slash in 'say', I get this error:

> Error:Unexpected token: {"type":"reg","value":"say"}
I get similiar errors with other commands like /scoreboard as well

**Comment by Pandawan** [comment]
Oh, the problem is, currently the execute block system is overriding the normal execute command.
Until I fix this (which should be soon), you will have to do it like this:
```
execute @e[score_text_min=0] ~ ~ ~ {
    say $y;
};
